import { useState } from 'react'

type Law = 'zipf' | 'menzerath' | 'uid' | 'arnon'

interface LawDef {
  id: Law
  label: string
  title: string
  formula?: string
  body: string
  crossspecies: string
  cite: string
  caution: string
}

const LAWS: LawDef[] = [
  {
    id: 'zipf',
    label: "Zipf's law",
    title: "Zipf's Law — Rank-Frequency Power Law",
    formula: 'P(w) ∝ rank(w)^{−α}  (α ≈ 1)',
    body: 'The frequency of any word is approximately inversely proportional to its rank in the frequency table. The most common word is roughly twice as frequent as the second most common, three times as frequent as the third, and so on. This holds across languages, text genres, and languages of every structural type. It also holds for music, protein sequences, and urban economics.',
    crossspecies: 'Zipfian rank-frequency distributions have been reported in humpback whale song syllables (Suzuki et al. 2006), vervet alarm calls, and dolphin whistle elements. The distribution follows from any system that communicates efficiently under bandwidth constraints — it is a consequence of optimizing for learnability and transmission efficiency, not a signature of language specifically.',
    cite: 'Zipf (1949); Piantadosi et al. (2014, PNAS); Mandelbrot (1953)',
    caution: 'Zipfian distributions are compatible with non-language systems generated by random concatenation with stop rules (Miller 1957). They are a necessary but not sufficient condition for language-like communication.',
  },
  {
    id: 'menzerath',
    label: 'Menzerath-Altmann',
    title: 'Menzerath-Altmann Law — Size-Complexity Trade-off',
    formula: 'L_constituent = a · L_whole^b · e^{−c·L_whole}',
    body: 'Longer linguistic constructs tend to have shorter sub-constituents: longer sentences have shorter words; longer words have shorter syllables. Originally described for human language (Menzerath 1954), then formalized by Altmann (1980). It is interpreted as a compression-efficiency principle: the system distributes complexity across levels to minimize total coding cost.',
    crossspecies: 'A Menzerath-Altmann-like law has been reported in gelada monkey call bouts (Gustison et al. 2016) and in humpback whale song hierarchy (McCowan et al.). This shows the law emerges from any hierarchically organized signal, not from language-specific structure. Gelada vocalizations are not compositional but still obey this law.',
    cite: 'Menzerath (1954); Altmann (1980); Gustison et al. (2016, PNAS)',
    caution: 'Menzerath-Altmann law follows from any hierarchical system subject to optimization pressure — including non-linguistic ones. Its presence is not evidence of compositionality or even grammar.',
  },
  {
    id: 'uid',
    label: 'Uniform Info. Density',
    title: 'Uniform Information Density (UID)',
    formula: 'argmin_{P(w|context)} Var[−log P(w|context)]',
    body: 'Speakers tend to distribute information roughly uniformly across an utterance — peaks of high information density (surprising words) are smoothed by using more predictable words nearby, inserting filled pauses, or lengthening durations. This avoids channel overload at high-surprise moments. Gibson et al. (2019, PNAS) showed this cross-linguistically: word order preferences and morphological choices correlate with UID across 80+ languages.',
    crossspecies: 'UID-like smoothing has been proposed for birdsong (birds insert lower-entropy syllables before high-entropy transitions). Whale song temporal structure may also reflect UID-like constraints. But the interpretation depends on whether the "channel" is a naive listener or a statistical model.',
    cite: 'Levy & Jaeger (2007, Psychological Science); Gibson et al. (2019, PNAS)',
    caution: 'UID is a production strategy, not a property of the signal alone. Measuring it requires a language model of the listener. Cross-species comparisons using UID require careful matching of the statistical model to the actual perceptual system of the receiver.',
  },
  {
    id: 'arnon',
    label: 'Arnon et al. 2025',
    title: 'Arnon et al. 2025 — Humpback Whale Compressibility',
    formula: 'Compressibility = 1 − |compressed| / |original|',
    body: 'Arnon et al. (2025, Science) applied lossless compression (Lempel-Ziv complexity) to humpback whale song sequences and human speech and found that humpback songs have the same compressibility signature as human speech corpora — significantly higher compressibility than random sequences and similar to human language corpora. The paper interpreted this as evidence of shared statistical structure.',
    crossspecies: 'The finding received enormous press attention as evidence that whale "language" is comparable to human language. But compressibility measures redundancy, not compositionality. A highly repetitive random string is very compressible. The study showed that whale song has a similar degree of statistical redundancy to human speech — not that it is compositional, referential, or syntactically structured.',
    cite: 'Arnon et al. (2025, Science); see also Piantadosi & Cantlon (2025) for rebuttal framing',
    caution: 'Compressibility ≠ compositionality ≠ language. The Arnon et al. 2025 result establishes that humpback whale song and human speech are similarly compressible. This says something about the distribution of sequence statistics but nothing about the referential, compositional, or pragmatic properties of whale communication. The gap between information-theoretic regularity and language remains wide.',
  },
]

/* Mock Zipf curve data */
const ZIPF_SYSTEMS = [
  { id: 'human',    label: 'Human language', color: '#c9a84c', alpha: 1.0 },
  { id: 'whale',    label: 'Humpback song',   color: '#4afdc6', alpha: 0.85 },
  { id: 'bird',     label: 'Bengalese finch', color: '#ffb472', alpha: 0.72 },
  { id: 'primate',  label: 'Vervet calls',    color: '#b57bee', alpha: 0.45 },
]

function zipfY(rank: number, alpha: number) {
  return 1 / Math.pow(rank, alpha)
}

export function HumanInfoTheory() {
  const [active, setActive] = useState<Law>('zipf')
  const [activeZipf, setActiveZipf] = useState<string>('human')

  const def = LAWS.find(l => l.id === active)!
  const maxRanks = 30
  const W = 520, H = 220
  const pad = { l: 50, r: 20, t: 20, b: 40 }
  const cw = W - pad.l - pad.r
  const ch = H - pad.t - pad.b

  function cx(rank: number) { return pad.l + (Math.log(rank) / Math.log(maxRanks)) * cw }
  function cy(freq: number) { return pad.t + (1 - Math.log1p(freq) / Math.log1p(1)) * ch }

  const zSys = ZIPF_SYSTEMS.find(s => s.id === activeZipf)!

  return (
    <div className="human-section">
      <p className="human-eyebrow">Human Language</p>
      <h1 className="human-title">Information Theory Across Species</h1>
      <p className="human-lede">
        Zipf's law, Menzerath-Altmann, and Uniform Information Density recur across every
        communication system in this series. This convergence reveals shared optimization
        pressures — not shared linguistic architecture. Compressibility is not compositionality.
      </p>

      {/* Law selector */}
      <div className="info-tabs">
        {LAWS.map(l => (
          <button
            key={l.id}
            className={`info-tab${active === l.id ? ' active' : ''}`}
            onClick={() => setActive(l.id)}
          >
            {l.label}
          </button>
        ))}
      </div>

      {active === 'zipf' && (
        <div className="info-zipf">
          <h2 className="human-h2">Rank–Frequency Curves</h2>
          <p className="human-sub">
            Log-rank vs. log-frequency plot. Slope ≈ −α. Click a system to compare.
          </p>
          <div className="zipf-sys-tabs">
            {ZIPF_SYSTEMS.map(s => (
              <button
                key={s.id}
                className={`zipf-sys-tab${activeZipf === s.id ? ' active' : ''}`}
                style={activeZipf === s.id ? { borderColor: s.color, color: s.color } : {}}
                onClick={() => setActiveZipf(s.id)}
              >
                {s.label}
              </button>
            ))}
          </div>
          <svg viewBox={`0 0 ${W} ${H}`} className="zipf-svg">
            {/* Axes */}
            <line x1={pad.l} y1={pad.t} x2={pad.l} y2={H - pad.b} stroke="var(--human-gold)" strokeWidth="1" opacity="0.4" />
            <line x1={pad.l} y1={H - pad.b} x2={W - pad.r} y2={H - pad.b} stroke="var(--human-gold)" strokeWidth="1" opacity="0.4" />
            <text x={W / 2} y={H - 8} textAnchor="middle" fill="var(--human-warm)" fontSize="10" fontFamily="var(--font-sans)">log rank →</text>
            <text x={14} y={H / 2} textAnchor="middle" fill="var(--human-warm)" fontSize="10" fontFamily="var(--font-sans)" transform={`rotate(-90 14 ${H / 2})`}>log frequency →</text>

            {/* All systems (faint) */}
            {ZIPF_SYSTEMS.filter(s => s.id !== activeZipf).map(s => {
              const pts = Array.from({ length: maxRanks }, (_, i) => {
                const rank = i + 1
                const freq = zipfY(rank, s.alpha)
                return `${cx(rank)},${cy(freq)}`
              }).join(' ')
              return <polyline key={s.id} points={pts} fill="none" stroke={s.color} strokeWidth="1" opacity="0.2" />
            })}

            {/* Active system */}
            {(() => {
              const pts = Array.from({ length: maxRanks }, (_, i) => {
                const rank = i + 1
                const freq = zipfY(rank, zSys.alpha)
                return `${cx(rank)},${cy(freq)}`
              }).join(' ')
              return <polyline points={pts} fill="none" stroke={zSys.color} strokeWidth="2.5" />
            })()}

            {/* Slope annotation */}
            <text x={W - pad.r - 10} y={pad.t + 20} textAnchor="end" fill={zSys.color} fontSize="11" fontFamily="var(--font-mono)">
              α ≈ {zSys.alpha.toFixed(2)}
            </text>
          </svg>
          <p className="zipf-note">
            The slope of the log-log plot gives the Zipfian exponent α. Human language hovers
            near α = 1 (Zipf's original observation). Humpback whale song syllables show
            a similar but shallower slope — indicating fewer high-frequency elements and a
            less extreme heavy tail. Both are Zipfian; they differ in the exponent.
          </p>
        </div>
      )}

      {/* Law detail */}
      <div className="info-detail">
        <h3 className="info-detail-title">{def.title}</h3>
        {def.formula && <code className="info-formula">{def.formula}</code>}
        <p className="info-body">{def.body}</p>

        <div className="info-cross">
          <span className="info-cross-label">Cross-species occurrence</span>
          <p className="info-cross-text">{def.crossspecies}</p>
        </div>

        <div className="info-cite">
          <span className="info-cite-label">Key citations:</span> {def.cite}
        </div>

        <div className="info-caution">
          <span className="info-caution-label">Caution:</span> {def.caution}
        </div>
      </div>

      <div className="human-callout">
        <div>
          <strong>The bottom line:</strong> Information-theoretic regularities (Zipf, Menzerath,
          UID) are universal optimization signatures — they emerge from any system under
          pressure to communicate efficiently over a limited-capacity channel. They are
          deeply interesting as convergences, but they are not evidence of compositionality,
          recursion, or any specifically linguistic property. The Arnon et al. 2025 result
          that humpback song and human speech are equally compressible is a statement about
          redundancy structure, not about meaning. The gap between regularity and language
          remains the central open question of the entire series.
        </div>
      </div>
    </div>
  )
}
